### ISSUE TITLE
no rendering ?

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/second-ros#1]
hey, guys,

thanks for this great work. 

I am playing with it today, but with a different purpose:  to see how the lg-simulator server works in Docker env (or you can help to explain directly).   so I exchanged  `/root/catkin_ws/src/second_ros/scripts/second_ros.py` with an empty.py,  ran `docker-compose up build`  again, and updated the docker-compose.yml  envrionment first as [discussed here](https://github.com/lgsvl/lanefollowing/issues/4)
  
```shell
      - ROS_MASTER_URI=http://172.17.0.1:11311 
      - ROS_IP=172.17.0.1
``` 

suppose the lg-simulator screen is there, but none. and the logs:

```bat
second-ros    | rviz::RenderSystem: error creating render window: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(1)' already exists in GLRenderSystem::_createRenderWindow at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1057)
second-ros    | [ERROR] [1562921161.169244893]: Unable to create the rendering window after 100 tries.
second-ros    | [rviz-4] process has died [pid 119, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /root/catkin_ws/src/second_ros/config/second_ros.rviz __name:=rviz __log:=/root/.ros/log/782414de-a481-11e9-ab62-c8d9d22439df/rviz-4.log].


# from rviz-*.log
^[[33m[ WARN] [1562921161.124956111]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1057)^[[0m

```

also tested with `glxgears` , which is running, but with a black/empty window

```shell 
root@ubuntu:~# apt-get install mesa-utils 
root@ubuntu:~# glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
295 frames in 5.0 seconds = 58.895 FPS
266 frames in 5.0 seconds = 53.151 FPS
300 frames in 5.0 seconds = 59.937 FPS
283 frames in 5.0 seconds = 56.523 FPS
245 frames in 5.0 seconds = 48.983 FPS
303 frames in 5.0 seconds = 60.402 FPS
``` 

any suggestions?  

Thanks
David

**Comment by daviduhm** [comment]
If I understood correctly, you replaced `second_ros.py` with an `empty.py` which doesn't have any code inside? When you run `docker-compose up second-ros`, it will internally run `scripts/build_and_run.sh` and launch 3 Ros nodes: rosbag, second_ros.py, and rviz. The launch file plays a sample rosbag and publishes Lidar messages to the ROS, and second-ros node subscribes to that topic, detects obstacles, and publishes bounding box messages back into ROS. If you replaced `second_ros.py` with a different file, the launch file will fail because it can't locate the node.

Then, rviz will finally visualize the point cloud messages with the final bounding boxes. It has nothing to do with our simulator and will not launch the simulator screen. Can you first try to follow the [instructions](https://github.com/lgsvl/second-ros/blob/master/README.md#getting-started) without any modifications and see if everything works fine?
